# Generated by Django 4.2.6 on 2023-10-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.IntegerField(default='Unknown Brand', primary_key=True, serialize=False)),
                ('brand', models.CharField(verbose_name=64)),
            ],
        ),
    ]
