# Generated by Django 4.2.6 on 2023-10-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_car', models.CharField(max_length=15)),
                ('horse_power', models.IntegerField(max_length=1000)),
                ('engine_capacity', models.FloatField(max_length=4)),
                ('gearbox', models.CharField(max_length=6)),
                ('year_release', models.IntegerField(max_length=5)),
                ('type_car', models.CharField(max_length=15)),
                ('fuel_grade', models.IntegerField(max_length=15)),
                ('cars_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cars')),
            ],
        ),
    ]
