# Generated by Django 4.2.6 on 2023-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='fuel_grade',
            field=models.CharField(max_length=10),
        ),
    ]
