# Generated by Django 4.2.6 on 2023-11-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_models_fuel_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='image_model',
            field=models.ImageField(blank=True, upload_to='models_images'),
        ),
    ]
